[package]
name = "vrch-headless"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# tauri requirements
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# project stuff
oyasumivr_oscquery = { git = "https://github.com/Raphiiko/oyasumivr_oscquery.git" }
tokio = "1.42.0"
rosc = { git = "https://github.com/virtuallyaverage/rosc-serde.git" }
winapi = {version = "0.3.9", features = ["winbase"] }
ctrlc = "3.4.5"

[profile.release]
debug = true